# Generated by Django 5.1.7 on 2025-04-03 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='1=Poor, 5=Excellent')),
                ('enjoyed_most', models.CharField(choices=[('Taste', 'Taste'), ('Presentation', 'Presentation'), ('Service', 'Service'), ('Ambience', 'Ambience'), ('Other', 'Other')], max_length=20, verbose_name='What did you enjoy most about your meal')),
                ('other_feedback', models.TextField(blank=True, null=True, verbose_name='Additional feedback')),
                ('would_recommend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Would you recommend our restaurant?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
